"""
Project Drishti — ML Model Trainer
Trains both WHEN (Kaplan-Meier Survival Analysis) and WHERE (LightGBM LambdaMART)
models on the synthetic dataset generated by Role 5.

Saves trained weights into ml_engine/weights/
"""

import os
import sys
import json
import pickle
import numpy as np
import pandas as pd

# Path setup
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(BASE_DIR)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
WEIGHTS_DIR = os.path.join(BASE_DIR, "weights")
os.makedirs(WEIGHTS_DIR, exist_ok=True)

SIM_DATA_DIR = os.path.join(PROJECT_ROOT, "simulation", "data")
ATMS_CSV = os.path.join(SIM_DATA_DIR, "atms_master.csv")
TXS_CSV = os.path.join(SIM_DATA_DIR, "historical_transactions.csv")
DIST_JSON = os.path.join(SIM_DATA_DIR, "distance_matrix.json")

def train_when_model():
    print("\n" + "="*60)
    print(">>> SECTION 1: TRAINING WHEN MODEL (SURVIVAL ANALYSIS) <<<")
    print("="*60)
    from lifelines import KaplanMeierFitter

    df = pd.read_csv(TXS_CSV)
    df["transfer_ts"] = pd.to_datetime(df["transfer_timestamp"])
    df["withdraw_ts"] = pd.to_datetime(df["withdrawal_timestamp"], errors="coerce")
    df["event_occurred"] = df["withdraw_ts"].notna().astype(int)

    # Calculate duration
    df["duration"] = (df["withdraw_ts"] - df["transfer_ts"]).dt.total_seconds() / 60

    # Censored duration = study elapsed time (or default reasonable cap)
    censored_mask = df["event_occurred"] == 0
    df.loc[censored_mask, "duration"] = 120.0
    df["duration"] = df["duration"].clip(lower=2.0, upper=240.0)

    # Filter to mule transactions
    mule_df = df[df["receiver_id"].str.startswith("ACC_MULE") | df["receiver_id"].str.startswith("MULE") | (df["amount"] >= 50000)].copy()
    if len(mule_df) == 0:
        mule_df = df

    print(f"[INFO] Fitting KaplanMeierFitter on {len(mule_df)} records...")
    print(f"[INFO] Observed cashouts: {mule_df['event_occurred'].sum()} | Censored: {(mule_df['event_occurred'] == 0).sum()}")

    kmf = KaplanMeierFitter()
    kmf.fit(
        durations=mule_df["duration"],
        event_observed=mule_df["event_occurred"],
        label="Mule Cashout Duration (mins)"
    )

    save_path = os.path.join(WEIGHTS_DIR, "survival_model.pkl")
    with open(save_path, "wb") as f:
        pickle.dump(kmf, f)

    median_mins = kmf.median_survival_time_
    print(f"[SUCCESS] Kaplan-Meier model saved to: {save_path}")
    print(f"[METRIC] Median cashout time: {median_mins:.1f} minutes")
    return kmf

def train_where_model():
    print("\n" + "="*60)
    print(">>> SECTION 2: TRAINING WHERE MODEL (LIGHTGBM LAMBDAMART) <<<")
    print("="*60)
    import lightgbm as lgb
    from ml_engine.models.ltr_ranker import prepare_ltr_training_data, FEATURE_NAMES

    # Sample top 200 fraud events to train quickly and avoid memory bloat
    tx_df = pd.read_csv(TXS_CSV)
    valid_txs = tx_df[tx_df["withdrawal_atm_id"].notna() & (tx_df["withdrawal_atm_id"] != "")]["tx_id"].unique()
    sample_tx_ids = set(valid_txs[:250])  # 250 queries x 180 ATMs = 45,000 candidate-event pairs

    # Temp file with sampled queries for fast training
    temp_csv = os.path.join(WEIGHTS_DIR, "temp_sampled_txs.csv")
    tx_df[tx_df["tx_id"].isin(sample_tx_ids)].to_csv(temp_csv, index=False)

    print(f"[INFO] Preparing LambdaMART features for {len(sample_tx_ids)} queries...")
    X, y, groups = prepare_ltr_training_data(temp_csv, ATMS_CSV, DIST_JSON)

    if os.path.exists(temp_csv):
        os.remove(temp_csv)

    print(f"[INFO] Dataset built: {len(X)} rows, {len(FEATURE_NAMES)} features across {len(groups)} ranking queries.")

    # Train / Test split (80/20)
    n_train_groups = int(len(groups) * 0.8)
    train_rows = sum(groups[:n_train_groups])
    
    X_train, y_train, groups_train = X.iloc[:train_rows], y[:train_rows], groups[:n_train_groups]
    X_val, y_val, groups_val = X.iloc[train_rows:], y[train_rows:], groups[n_train_groups:]

    train_data = lgb.Dataset(X_train, label=y_train, group=groups_train)
    val_data = lgb.Dataset(X_val, label=y_val, group=groups_val, reference=train_data)

    params = {
        "objective": "lambdarank",
        "metric": "ndcg",
        "ndcg_eval_at": [1, 3, 5],
        "learning_rate": 0.08,
        "num_leaves": 31,
        "feature_fraction": 0.85,
        "min_data_in_leaf": 10,
        "verbosity": -1
    }

    print("[INFO] Training LambdaMART model...")
    model = lgb.train(
        params,
        train_data,
        num_boost_round=120,
        valid_sets=[val_data]
    )

    save_path = os.path.join(WEIGHTS_DIR, "ltr_model.txt")
    model.save_model(save_path)
    print(f"[SUCCESS] LambdaMART model saved to: {save_path}")

    # Feature importances
    importances = model.feature_importance(importance_type='gain')
    print("\n[INFO] Top Feature Importances (Gain):")
    for fname, imp in sorted(zip(FEATURE_NAMES, importances), key=lambda x: x[1], reverse=True)[:5]:
        print(f"   - {fname:25}: {imp:.2f}")

    return model

if __name__ == "__main__":
    train_when_model()
    train_where_model()
    print("\n" + "="*60)
    print(">>> ALL ML MODELS TRAINED & VALIDATED SUCCESSFULLY! <<<")
    print("="*60)
